name: Run updater

on:
  workflow_dispatch:
  schedule:
    - cron: "0 20 * * *"

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run script
        run: python update_nem_data.py
